### ISSUE TITLE
Linktap (Reinstalled) nodeserver sees valves but all data is zero or false and commands wont work

### ISSUE THREAD

**Issue by macjeff** [simplextech/udi-poly-linktap#11]
This was working fine but have had valves turned off and inside for winter.  New batteries and works FINE from the LinkTap app but getting errors in the logs.   
<img width="1382" alt="Screen Shot 2021-04-28 at 3 58 38 PM" src="https://user-images.githubusercontent.com/20373758/116476051-af793500-a848-11eb-9f51-ebd83f7cfece.png">
<img width="1377" alt="Screen Shot 2021-04-28 at 3 58 45 PM" src="https://user-images.githubusercontent.com/20373758/116476053-af793500-a848-11eb-8d38-c3cb00a6403f.png">
<img width="1395" alt="Screen Shot 2021-04-28 at 3 58 51 PM" src="https://user-images.githubusercontent.com/20373758/116476054-af793500-a848-11eb-926e-4b8c7ec5448a.png">
<img width="1390" alt="Screen Shot 2021-04-28 at 3 58 56 PM" src="https://user-images.githubusercontent.com/20373758/116476057-af793500-a848-11eb-9c1c-f1bf690d4de9.png">

Sent info to you in UDI via PM so you could see my system live.  Here are some logs with errors

2021-04-28 15:59:09,270 MQTT       polyinterface      DEBUG    polyinterface:_message: Received stop from Polyglot... Shutting Down.
2021-04-28 15:59:09,271 MQTT       polyinterface      INFO     polyinterface:stop: Disconnecting from MQTT... localhost:1883
2021-04-28 15:59:09,273 MQTT       polyinterface      DEBUG    LinkTap:stop: NodeServer stopped.
2021-04-28 15:59:09,274 MQTT       polyinterface      INFO     polyinterface:_disconnect: MQTT Graceful disconnection.
2021-04-28 15:59:09,276 MQTT       polyinterface      DEBUG    polyinterface:_startMqtt: MQTT Done:
2021-04-28 15:59:12,861 MainThread polyinterface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2021-04-28 15:59:13,949 MainThread polyinterface      INFO     polyinterface:init_interface: Received Config from STDIN.
2021-04-28 15:59:13,950 MainThread polyinterface      INFO     __init__:<module>: UDI Polyglot v2 Interface 2.1.0 Starting...
2021-04-28 15:59:15,077 MainThread polyinterface      DEBUG    polyinterface:get_network_interface: gws: {'default': {2: ('172.16.1.1', 'igb0')}, 2: [('172.16.1.1', 'igb0', True)]}
2021-04-28 15:59:15,079 MainThread polyinterface      DEBUG    polyinterface:get_network_interface: gw: default=('172.16.1.1', 'igb0')
2021-04-28 15:59:15,080 MainThread polyinterface      DEBUG    polyinterface:get_network_interface: ifad: igb0=[{'addr': '172.16.1.226', 'netmask': '255.255.255.0', 'broadcast': '172.16.1.255'}]
2021-04-28 15:59:15,081 MainThread polyinterface      INFO     polyinterface:__init__: Connect: Network Interface: {'addr': '172.16.1.226', 'netmask': '255.255.255.0', 'broadcast': '172.16.1.255'}
2021-04-28 15:59:15,084 Interface  polyinterface      INFO     polyinterface:_startMqtt: Connecting to MQTT... localhost:1883
2021-04-28 15:59:15,284 MQTT       polyinterface      INFO     polyinterface:_connect: MQTT Connected with result code 0 (Success)
2021-04-28 15:59:15,286 MQTT       polyinterface      INFO     polyinterface:_connect: MQTT Subscribing to topic: udi/polyglot/ns/6 -  MID: 1 Result: 0
2021-04-28 15:59:15,287 MQTT       polyinterface      INFO     polyinterface:_connect: MQTT Subscribing to topic: udi/polyglot/connections/polyglot -  MID: 2 Result: 0
2021-04-28 15:59:15,288 MQTT       polyinterface      INFO     polyinterface:_connect: Sent Connected message to Polyglot
2021-04-28 15:59:15,386 MQTT       polyinterface      INFO     polyinterface:_subscribe: MQTT Subscribed Succesfully for Message ID: 1 - QoS: (0,)
2021-04-28 15:59:15,428 MQTT       polyinterface      INFO     polyinterface:_subscribe: MQTT Subscribed Succesfully for Message ID: 2 - QoS: (0,)
2021-04-28 15:59:15,511 NodeServer polyinterface      INFO     LinkTap:start: Started LinkTap NodeServer
2021-04-28 15:59:15,513 NodeServer polyinterface      INFO     polyinterface:saveCustomParams: Sending customParams to Polyglot.
2021-04-28 15:59:17,649 NodeServer polyinterface      INFO     LinkTap:remove_notices_all: remove_notices_all: notices={}
2021-04-28 15:59:17,959 NodeServer polyinterface      INFO     polyinterface:addNode: Adding node Main gateway(2abd291f)
2021-04-28 15:59:19,995 NodeServer polyinterface      INFO     polyinterface:addNode: Adding node Valve 1- Berry Line(b95fc21e)
2021-04-28 15:59:20,148 Controller polyinterface      INFO     polyinterface:reportDriver: Updating Driver b95fc21e - ST: 1, uom: 2
2021-04-28 15:59:20,151 Controller polyinterface      INFO     polyinterface:reportDriver: Updating Driver b95fc21e - BATLVL: 100, uom: 51
2021-04-28 15:59:20,166 Controller polyinterface      ERROR    polyinterface:write: Exception in thread Controller:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/var/polyglot/.local/lib/python3.7/site-packages/polyinterface/polyinterface.py", line 848, in _parseInput
    self._handleResult(input[key])
  File "/var/polyglot/.local/lib/python3.7/site-packages/polyinterface/polyinterface.py", line 873, in _handleResult
    self.nodes[result['addnode']['address']].start()
  File "./LinkTap.py", line 285, in start
    self.setDriver('GV0', tl['signal'].strip('%'), force=True)
AttributeError: 'int' object has no attribute 'strip'
2021-04-28 15:59:22,026 NodeServer polyinterface      INFO     polyinterface:addNode: Adding node Valve 2- Fruit Trees(0c61c21e)
2021-04-28 15:59:24,089 NodeServer polyinterface      INFO     polyinterface:addNode: Adding node Valve 3- Pool Fill(805dc21e)
2021-04-28 15:59:26,160 NodeServer polyinterface      INFO     polyinterface:addNode: Adding node Valve 4- Deck Hose(3161c21e)
2021-04-28 15:59:28,166 NodeServer polyinterface      ERROR    polyinterface:write: Exception in thread NodeServer:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./LinkTap.py", line 34, in start
    self.discover()
  File "./LinkTap.py", line 156, in discover
    self.update()
  File "./LinkTap.py", line 114, in update
    self.nodes[node].setDriver('GV0', tl['signal'].strip('%'), force=False)
AttributeError: 'int' object has no attribute 'strip'

**Comment by macjeff** [comment]
All the info in the pictrures is bogus.  Except Valve one online is true and battery is 100% but signal in app shows almost 100% for all the valves, they are all online, and ALL at 100% battery.

**Comment by simplextech** [comment]
Problem should be resolved.  Update the nodeserver and restart.  LinkTap changed their API and removed the % from the signal return value which was causing the nodeserver to exit on refresh of data.

**Comment by macjeff** [comment]
New version fixed my issues.   Note this version is 0.1.3.0    Stop node server, update nodeserver, and then I usually click on restart.  You should see version go to 0.1.3.0.  If it stays on old 0.1.2.9 version then you will have to do what I did, uninstall and reinstall.  For some reason the update was not coming in but issue could be on the Polisy Nodeserver store.

**Comment by macjeff** [comment]
working great now.  You may have to reinstall due to some back end changes.
